#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ easy x86_24h -1
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ easy x86_24h 2
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ easy x86_24h 3
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ easy x86_24h 4
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ easy x86_24h 5
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ easy x86_24h 6
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ easy x86_24h 7
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ easy x86_24h 8
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ easy x86_24h 9
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ easy x86_24h 12
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ easy x86_24h 13
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ easy x86_24h 14
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ easy x86_24h 15
#./run_test.sh model_softmax_decoder_newversion/ easy x86_6h -1
#./run_test.sh model_softmax_decoder_newversion/ easy x86_6h 2
./run_test.sh model_softmax_decoder_newversion/ easy x86_6h 3
./run_test.sh model_softmax_decoder_newversion/ easy x86_6h 4
./run_test.sh model_softmax_decoder_newversion/ easy x86_6h 5
./run_test.sh model_softmax_decoder_newversion/ easy x86_6h 6
./run_test.sh model_softmax_decoder_newversion/ easy x86_6h 7
./run_test.sh model_softmax_decoder_newversion/ easy x86_6h 8
./run_test.sh model_softmax_decoder_newversion/ easy x86_6h 9
./run_test.sh model_softmax_decoder_newversion/ easy x86_6h 10
#./run_test.sh model_softmax_decoder_newversion/ easy x86_6h 11
./run_test.sh model_softmax_decoder_newversion/ easy x86_6h 12
./run_test.sh model_softmax_decoder_newversion/ easy x86_6h 13
./run_test.sh model_softmax_decoder_newversion/ easy x86_6h 14
./run_test.sh model_softmax_decoder_newversion/ easy x86_6h 15
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ hard x86_24h -1
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ hard x86_24h 2
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ hard x86_24h 3
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ hard x86_24h 4
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ hard x86_24h 5
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ hard x86_24h 6
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ hard x86_24h 7
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ hard x86_24h 8
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ hard x86_24h 9
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ hard x86_24h 10
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ hard x86_24h 11
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ hard x86_24h 12
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ hard x86_24h 13
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ hard x86_24h 14
#./run_test.sh model_softmax_kvmem_validtrim_unfilt_newversion/ hard x86_24h 15
#./run_test.sh model_softmax_decoder_newversion/ hard x86_24h -1
#./run_test.sh model_softmax_decoder_newversion/ hard x86_24h 2
./run_test.sh model_softmax_decoder_newversion/ hard x86_24h 3
./run_test.sh model_softmax_decoder_newversion/ hard x86_24h 4
./run_test.sh model_softmax_decoder_newversion/ hard x86_24h 5
./run_test.sh model_softmax_decoder_newversion/ hard x86_24h 6
./run_test.sh model_softmax_decoder_newversion/ hard x86_24h 7
./run_test.sh model_softmax_decoder_newversion/ hard x86_24h 8
./run_test.sh model_softmax_decoder_newversion/ hard x86_24h 9
./run_test.sh model_softmax_decoder_newversion/ hard x86_24h 10
#./run_test.sh model_softmax_decoder_newversion/ hard x86_24h 11
./run_test.sh model_softmax_decoder_newversion/ hard x86_24h 12
./run_test.sh model_softmax_decoder_newversion/ hard x86_24h 13
./run_test.sh model_softmax_decoder_newversion/ hard x86_24h 14
./run_test.sh model_softmax_decoder_newversion/ hard x86_24h 15
