#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_-1/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_-1/top20_ent_from_mem.txt 2
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_-1/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_-1/top20_ent_from_mem.txt 5
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_-1/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_-1/top20_ent_from_mem.txt 10
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_-1/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_-1/top20_ent_from_mem.txt 20

#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_3/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_3/top20_ent_from_mem.txt 2
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_3/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_3/top20_ent_from_mem.txt 5
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_3/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_3/top20_ent_from_mem.txt 10
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_3/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_3/top20_ent_from_mem.txt 20

#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_4/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_4/top20_ent_from_mem.txt 2
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_4/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_4/top20_ent_from_mem.txt 5
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_4/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_4/top20_ent_from_mem.txt 10
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_4/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_4/top20_ent_from_mem.txt 20

#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_5/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_5/top20_ent_from_mem.txt 2
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_5/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_5/top20_ent_from_mem.txt 5
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_5/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_5/top20_ent_from_mem.txt 10
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_5/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_5/top20_ent_from_mem.txt 20

#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_6/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_6/top20_ent_from_mem.txt 2
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_6/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_6/top20_ent_from_mem.txt 5
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_6/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_6/top20_ent_from_mem.txt 10
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_6/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_6/top20_ent_from_mem.txt 20

#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7/top20_ent_from_mem.txt 2
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7/top20_ent_from_mem.txt 5
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7/top20_ent_from_mem.txt 10
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7/top20_ent_from_mem.txt 20

#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7a/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7a/top20_ent_from_mem.txt 2
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7a/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7a/top20_ent_from_mem.txt 5
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7a/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7a/top20_ent_from_mem.txt 10
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7a/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7a/top20_ent_from_mem.txt 20

#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7b/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7b/top20_ent_from_mem.txt 2
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7b/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7b/top20_ent_from_mem.txt 5
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7b/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7b/top20_ent_from_mem.txt 10
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7b/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7b/top20_ent_from_mem.txt 20

#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8/top20_ent_from_mem.txt 2
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8/top20_ent_from_mem.txt 5
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8/top20_ent_from_mem.txt 10
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8/top20_ent_from_mem.txt 20

#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8a/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8a/top20_ent_from_mem.txt 2
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8a/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8a/top20_ent_from_mem.txt 5
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8a/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8a/top20_ent_from_mem.txt 10
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8a/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8a/top20_ent_from_mem.txt 20

#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8b/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8b/top20_ent_from_mem.txt 2
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8b/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8b/top20_ent_from_mem.txt 5
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8b/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8b/top20_ent_from_mem.txt 10
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8b/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8b/top20_ent_from_mem.txt 20

#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_9/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_9/top20_ent_from_mem.txt 2
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_9/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_9/top20_ent_from_mem.txt 5
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_9/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_9/top20_ent_from_mem.txt 10
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_9/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_9/top20_ent_from_mem.txt 20

#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_10/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_10/top20_ent_from_mem.txt 2
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_10/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_10/top20_ent_from_mem.txt 5
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_10/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_10/top20_ent_from_mem.txt 10
#python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_10/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_10/top20_ent_from_mem.txt 20

python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_12/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_12/top20_ent_from_mem.txt 2
python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_12/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_12/top20_ent_from_mem.txt 5
python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_12/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_12/top20_ent_from_mem.txt 10
python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_12/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_12/top20_ent_from_mem.txt 20

python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_13/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_13/top20_ent_from_mem.txt 2
python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_13/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_13/top20_ent_from_mem.txt 5
python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_13/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_13/top20_ent_from_mem.txt 10
python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_13/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_13/top20_ent_from_mem.txt 20

python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_14/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_14/top20_ent_from_mem.txt 2
python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_14/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_14/top20_ent_from_mem.txt 5
python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_14/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_14/top20_ent_from_mem.txt 10
python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_14/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_14/top20_ent_from_mem.txt 20

python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_15/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_15/top20_ent_from_mem.txt 2
python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_15/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_15/top20_ent_from_mem.txt 5
python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_15/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_15/top20_ent_from_mem.txt 10
python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_hard_15/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_hard_15/top20_ent_from_mem.txt 20


python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_easy_12/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_easy_12/top20_ent_from_mem.txt 2
python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_easy_12/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_easy_12/top20_ent_from_mem.txt 5
python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_easy_12/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_easy_12/top20_ent_from_mem.txt 10
python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_easy_12/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_easy_12/top20_ent_from_mem.txt 20

python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_easy_13/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_easy_13/top20_ent_from_mem.txt 2
python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_easy_13/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_easy_13/top20_ent_from_mem.txt 5
python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_easy_13/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_easy_13/top20_ent_from_mem.txt 10
python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_easy_13/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_easy_13/top20_ent_from_mem.txt 20

python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_easy_14/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_easy_14/top20_ent_from_mem.txt 2
python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_easy_14/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_easy_14/top20_ent_from_mem.txt 5
python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_easy_14/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_easy_14/top20_ent_from_mem.txt 10
python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_easy_14/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_easy_14/top20_ent_from_mem.txt 20

python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_easy_15/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_easy_15/top20_ent_from_mem.txt 2
python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_easy_15/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_easy_15/top20_ent_from_mem.txt 5
python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_easy_15/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_easy_15/top20_ent_from_mem.txt 10
python compute_recall.py model_softmax_kvmem_valid_trip_unfilt/test_output_easy_15/gold_ent.txt model_softmax_kvmem_valid_trip_unfilt/test_output_easy_15/top20_ent_from_mem.txt 20
