# cp model_softmax_kvmem_valid_trip_unfilt/test_output_hard_3/top20_ent_id_from_mem.txt model_softmax_kvmem_valid_trip_unfilt/prec_files/hard/top20_ent_id_from_mem_3.txt
# cp model_softmax_kvmem_valid_trip_unfilt/test_output_hard_4/top20_ent_id_from_mem.txt model_softmax_kvmem_valid_trip_unfilt/prec_files/hard/top20_ent_id_from_mem_4.txt
# cp model_softmax_kvmem_valid_trip_unfilt/test_output_hard_5/top20_ent_id_from_mem.txt model_softmax_kvmem_valid_trip_unfilt/prec_files/hard/top20_ent_id_from_mem_5.txt
# cp model_softmax_kvmem_valid_trip_unfilt/test_output_hard_6/top20_ent_id_from_mem.txt model_softmax_kvmem_valid_trip_unfilt/prec_files/hard/top20_ent_id_from_mem_6.txt
# cp model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7/top20_ent_id_from_mem.txt model_softmax_kvmem_valid_trip_unfilt/prec_files/hard/top20_ent_id_from_mem_7.txt
# cp model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8/top20_ent_id_from_mem.txt model_softmax_kvmem_valid_trip_unfilt/prec_files/hard/top20_ent_id_from_mem_8.txt
# cp model_softmax_kvmem_valid_trip_unfilt/test_output_hard_9/top20_ent_id_from_mem.txt model_softmax_kvmem_valid_trip_unfilt/prec_files/hard/top20_ent_id_from_mem_9.txt
# cp model_softmax_kvmem_valid_trip_unfilt/test_output_hard_10/top20_ent_id_from_mem.txt model_softmax_kvmem_valid_trip_unfilt/prec_files/hard/top20_ent_id_from_mem_10.txt

cp model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7a/top20_ent_id_from_mem.txt model_softmax_kvmem_valid_trip_unfilt/prec_files/hard/top20_ent_id_from_mem_7a.txt
cp model_softmax_kvmem_valid_trip_unfilt/test_output_hard_7b/top20_ent_id_from_mem.txt model_softmax_kvmem_valid_trip_unfilt/prec_files/hard/top20_ent_id_from_mem_7b.txt

cp model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8a/top20_ent_id_from_mem.txt model_softmax_kvmem_valid_trip_unfilt/prec_files/hard/top20_ent_id_from_mem_8a.txt
cp model_softmax_kvmem_valid_trip_unfilt/test_output_hard_8b/top20_ent_id_from_mem.txt model_softmax_kvmem_valid_trip_unfilt/prec_files/hard/top20_ent_id_from_mem_8b.txt